install the pyqrcode pakage for vscode
# pip install Keras
# pip install tensorFlow


# Keras Features


In [16]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.optimizers import Adam
from keras.utils import to_categorical
from keras.layers import Conv2D, MaxPooling2D
import cv2

# Load and preprocess the MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1).astype('float32')
X_train /= 255
X_test /= 255

number_of_classes = 10
y_train = to_categorical(y_train, number_of_classes)
y_test = to_categorical(y_test, number_of_classes)

# Create the model
model = Sequential()
model.add(Conv2D(32, (5, 5), input_shape=(X_train.shape[1], X_train.shape[2], 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(number_of_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5, batch_size=200)

# Load and preprocess the test image
img = cv2.imread('C:/Users/User/Downloads/10 img (1).png', cv2.IMREAD_GRAYSCALE)
resized = cv2.resize(img, (28, 28), interpolation=cv2.INTER_AREA)
img = np.resize(resized, (28, 28, 1))
im2arr = np.array(img)
im2arr = im2arr.reshape(1, 28, 28, 1)

# Make predictions and get the digit output
y_pred = model.predict(im2arr)
digit = np.argmax(y_pred)

print("Predicted Digit:", digit)

Epoch 1/5
300/300 [==============================] - 24s 77ms/step - loss: 0.4774 - accuracy: 0.8474 - val_loss: 0.0802 - val_accuracy: 0.9748
Epoch 2/5
300/300 [==============================] - 23s 77ms/step - loss: 0.1528 - accuracy: 0.9543 - val_loss: 0.0509 - val_accuracy: 0.9833
Epoch 3/5
300/300 [==============================] - 23s 77ms/step - loss: 0.1170 - accuracy: 0.9648 - val_loss: 0.0393 - val_accuracy: 0.9872
Epoch 4/5
300/300 [==============================] - 23s 77ms/step - loss: 0.0985 - accuracy: 0.9701 - val_loss: 0.0368 - val_accuracy: 0.9885
Epoch 5/5
1/1 [==============================] - 0s 51ms/step
Predicted Digit: 8


In [10]:
import cv2
import numpy as np
img = cv2.imread("C:/Users/User/Pictures/10 img.jfif", cv2.IMREAD_GRAYSCALE)
# resize image
resized = cv2.resize(img, (28,28), interpolation = cv2.INTER_AREA)
img = np.resize(resized, (28,28,1))
im2arr = np.array(img)
im2arr = im2arr.reshape(1,28,28,1)
y_pred = model.predict(im2arr)
predicted_digit=np.argmax(y_pred)
print(y_pred)
print(predicted_digit)
model.save('model.h5')


1/1 [==============================] - 0s 26ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
8


In [23]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Example categorical labels
labels = ['cat', 'dog', 'bird', 'dog', 'cat']

# Create a dictionary to map unique label strings to numerical values
label_map = {label: idx for idx, label in enumerate(set(labels))}

# Convert string labels to numerical categorical labels
numerical_labels = [label_map[label] for label in labels]

# Perform one-hot encoding
encoded_labels = to_categorical(numerical_labels)

print(encoded_labels)



[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


# Keras with Timeseries:

In [ ]:

import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Generate synthetic timeseries data
def generate_timeseries_data(n_steps):
    time = np.linspace(0, 2*np.pi, n_steps)
    data = np.sin(time) + np.random.normal(0, 0.1, n_steps)
    return data

n_steps = 100
data = generate_timeseries_data(n_steps)

# Prepare data for LSTM (input and target)
X = data[:-1]
y = data[1:]


# Reshape data for LSTM (samples, timesteps, features)
X = X.reshape(-1, 1, 1)

# Create LSTM model
model = Sequential()
model.add(LSTM(32, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=100, batch_size=1)



Epoch 1/100
99/99 [==============================] - 1s 958us/step - loss: 0.3952
Epoch 2/100
99/99 [==============================] - 0s 865us/step - loss: 0.1940
Epoch 3/100
99/99 [==============================] - 0s 906us/step - loss: 0.0519
Epoch 4/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0232
Epoch 5/100
99/99 [==============================] - 0s 896us/step - loss: 0.0228
Epoch 6/100
99/99 [==============================] - 0s 865us/step - loss: 0.0223
Epoch 7/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0222
Epoch 8/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0227
Epoch 9/100
99/99 [==============================] - 0s 865us/step - loss: 0.0225
Epoch 10/100
99/99 [==============================] - 0s 916us/step - loss: 0.0224
Epoch 11/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0224
Epoch 12/100
99/99 [==============================] - 0s 855us/step - loss: 0.0225
Epoch 13/100
99/99 [=

# Loading Data, defining Training models and predict results in Keras

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from keras.models import Sequential
from keras.layers import Dense

# Create the MLP model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)


# Make predictions on new data
new_data = [[5.1, 3.5, 1.4, 0.2], [6.4, 3.2, 4.5, 1.5], [7.3, 2.9, 6.3, 1.8]]


predictions = model.predict(new_data)

# Convert predictions to class labels
predicted_classes = [iris.target_names[pred.argmax()] for pred in predictions]
print("Predicted Classes:", predicted_classes)


Epoch 1/50
4/4 [==============================] - 1s 48ms/step - loss: 1.9048 - accuracy: 0.3519 - val_loss: 2.1018 - val_accuracy: 0.1667
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 1.8257 - accuracy: 0.3519 - val_loss: 2.0055 - val_accuracy: 0.1667
Epoch 3/50
4/4 [==============================] - 0s 7ms/step - loss: 1.7546 - accuracy: 0.3519 - val_loss: 1.9096 - val_accuracy: 0.1667
Epoch 4/50
4/4 [==============================] - 0s 9ms/step - loss: 1.6845 - accuracy: 0.3519 - val_loss: 1.8157 - val_accuracy: 0.1667
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 1.6241 - accuracy: 0.3519 - val_loss: 1.7241 - val_accuracy: 0.1667
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 1.5568 - accuracy: 0.3519 - val_loss: 1.6423 - val_accuracy: 0.1667
Epoch 7/50
4/4 [==============================] - 0s 9ms/step - loss: 1.4995 - accuracy: 0.3519 - val_loss: 1.5686 - val_accuracy: 0.1667
Epoch 8/50
4/4 [=================

# Keras with Support Vector Machine(SVM):

In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from keras.models import Sequential
from keras.layers import Dense

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the SVM model using SVC from scikit-learn
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

# Evaluate the SVM model
accuracy = svm_model.score(X_test, y_test)
print("SVM accuracy:", accuracy)

# Alternatively, you can use Keras to build an SVM-like model
model = Sequential()
model.add(Dense(1, input_dim=4, activation='linear'))
model.compile(optimizer='adam', loss='hinge', metrics=['accuracy'])

# Train the SVM-like model
model.fit(X_train, y_train, epochs=100, batch_size=32)

# Evaluate the SVM-like model
_, accuracy = model.evaluate(X_test, y_test)
print("SVM-like model accuracy:", accuracy)


SVM accuracy: 1.0
Epoch 1/100
4/4 [==============================] - 1s 5ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 4/100
4/4 [==============================] - 0s 998us/step - loss: 0.3333 - accuracy: 0.3417
Epoch 5/100
4/4 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 9/100
4/4 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 10/100
4/4 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.3417
Epoch 11/

# Keras with reinforcement learning

In [3]:

import gym
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Create the CartPole environment
env = gym.make('CartPole-v1')

# Q-learning algorithm
def q_learning(env, episodes=1000, alpha=0.1, gamma=0.99, epsilon=0.1):
    n_actions = env.action_space
    n_states = env.observation_space.shape[0]
    q_table = np.zeros((n_states, n_actions))
    

    for episode in range(episodes):
        state = env.reset()
        done = False

        while not done:
            if float (np.random.rand()) < epsilon:
                action = env.action_space.sample()
            else:
                action = np.argmax(q_table[state, :])

            next_state, reward, done, _ = env.step(action)

            q_next = np.max(q_table[next_state, :])
            q_table[state, action] = (1 - alpha) * q_table[state, action] + alpha * (reward + gamma * q_next)

            state = next_state
           

    return q_table




    

# Train Q-learning agent
q_table = q_learning(env)

print(q_table)

# Test the agent
state = env.reset()
done = False

while not done:
    action = np.argmax(q_table[state, :])
    next_state, _, done, _ = env.step(action)
    env.render()
    state = next_state

env.close()


TypeError: 'Discrete' object cannot be interpreted as an integer

In [11]:
import numpy as np
import gym

def q_learning(env, episodes=1000, alpha=0.1, gamma=0.99, epsilon=0.1):
    n_actions = env.action_space.n
    n_states = env.observation_space.shape[0]
    q_table = np.zeros((n_states, n_actions))
    
    for episode in range(episodes):
        state = env.reset()
        done = False
        
        while not done:
            if np.random.rand() < epsilon:
                action = np.random.choice(n_actions)
            else:
                action = np.argmax(q_table[state, :])
            
            next_state, reward, done, _ = env.step(action)
            
            q_value = q_table[state, action]
            next_q_max = np.max(q_table[next_state, :])
            
            new_q_value = (1 - alpha) * q_value + alpha * (reward + gamma * next_q_max)
            q_table[state, action] = new_q_value
            
            state = next_state
    
    return q_table


# Create the environment (replace 'CartPole-v1' with your desired environment)
env = gym.make('CartPole-v1')


# Train Q-learning agent
q_table = q_learning(env)

print(q_table)


C:\Users\User\AppData\Local\Temp\ipykernel_10204\2262461823.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  action = np.argmax(q_table[state, :])


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [21]:
import numpy as np
import gym

def q_learning(env, episodes=1000, alpha=0.1, gamma=0.99, epsilon=0.1):
    n_actions = env.action_space.n
    n_states = env.observation_space.shape[0]
    q_table = np.zeros((n_states, n_actions))

    # Rest of your Q-learning implementation here

    return q_table

# Create the environment
env = gym.make("CartPole-v1")

# Train Q-learning agent for 1000 episodes (you can change this number as needed)
q_table = q_learning(env, episodes=1000)

print(q_table)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [1]:
# import numpy as np
# N=np.random.rand()
# N 

N=int(input("enter the number"))

print(n_actions)

3.0


In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Generate synthetic timeseries data
def generate_timeseries_data(n_steps):
    time = np.linspace(0, 2*np.pi, n_steps)
    data = np.sin(time) + np.random.normal(0, 0.1, n_steps)
    return data

n_steps = 100
data = generate_timeseries_data(n_steps)

# Prepare data for LSTM (input and target)
X = data[:-1]
y = data[1:]

# Reshape data for LSTM (samples, timesteps, features)
X = X.reshape(-1, 1, 1)

# Create LSTM model
model = Sequential()
model.add(LSTM(32, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=100, batch_size=1)



Epoch 1/100
99/99 [==============================] - 1s 1ms/step - loss: 0.4214
Epoch 2/100
99/99 [==============================] - 0s 987us/step - loss: 0.2160
Epoch 3/100
99/99 [==============================] - 0s 997us/step - loss: 0.0636
Epoch 4/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0276
Epoch 5/100
99/99 [==============================] - 0s 967us/step - loss: 0.0269
Epoch 6/100
99/99 [==============================] - 0s 967us/step - loss: 0.0269
Epoch 7/100
99/99 [==============================] - 0s 987us/step - loss: 0.0277
Epoch 8/100
99/99 [==============================] - 0s 977us/step - loss: 0.0270
Epoch 9/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0271
Epoch 10/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0267
Epoch 11/100
99/99 [==============================] - 0s 967us/step - loss: 0.0266
Epoch 12/100
99/99 [==============================] - 0s 967us/step - loss: 0.0269
Epoch 13/100
99/99 [=

In [ ]:
import numpy as np

from tensorflow.keras.utils import to_categorical
# Example categorical labels
labels = ['cat', 'dog', 'bird', 'dog', 'cat']
# Perform one-hot encoding
encoded_labels = to_categorical(labels)
print(encoded_labels)


In [8]:
import gym
import numpy as np
import tensorflow as tf
import math
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create the CartPole environment
env = gym.make('CartPole-v1')

# Function to discretize the continuous state space
def discretize_state(state, n_buckets=(1, 1, 6, 12), state_bounds=None):
    if state_bounds is None:
        state_bounds = list(zip(env.observation_space.low, env.observation_space.high))
        state_bounds[1] = [-0.5, 0.5]
        state_bounds[3] = [-math.radians(50), math.radians(50)]

    discretized_state = []
    for i in range(len(state)):
        value = state[i]
        lower_bound, upper_bound = state_bounds[i]
        n_bins = n_buckets[i]
        discretized_value = np.linspace(lower_bound, upper_bound, n_bins + 1)[1:-1]
        discretized_state.append(np.digitize(value, discretized_value))
    return tuple(discretized_state)

# Q-learning algorithm
def q_learning(env, episodes=2000, alpha=0.1, gamma=0.99, epsilon=0.1):
    n_actions = env.action_space.n
    n_states = tuple((x + 1 for x in [1, 1, 6, 12]))  # Add 1 to each dimension to account for discretization

    q_table = np.zeros(n_states + (n_actions,))

    for episode in range(episodes):
        state = env.reset()
        state = discretize_state(state)  # Convert the state to a tuple
        done = False

        while not done:
            if np.random.rand() < epsilon:
                action = env.action_space.sample()
            else:
                action = np.argmax(q_table[state])

            next_state, reward, done, _ = env.step(action)
            next_state = discretize_state(next_state)

            q_next = np.max(q_table[next_state])
            q_table[state][action] = (1 - alpha) * q_table[state][action] + alpha * (reward + gamma * q_next)

            state = next_state

    return q_table

# Train Q-learning agent
q_table = q_learning(env)

# Test the agent
state = env.reset()
state = discretize_state(state)
done = False

while not done:
    action = np.argmax(q_table[state])
    next_state, _, done, _ = env.step(action)
    env.render()
    state = discretize_state(next_state)

env.close()


TypeError: '<' not supported between instances of 'dict' and 'dict'

In [7]:
import gym
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from collections import deque
import random
# from keras import utils
# from keras import utils



# Create the CartPole environmen
env = gym.make('CartPole-v1')

state_size = env.observation_space.shape[0]
action_size = env.action_space.n

# Define the DQN model
model = Sequential([
    Dense(24, input_dim=state_size, activation='relu'),
    Dense(24, activation='relu'),
    Dense(action_size, activation='linear')
])

model.compile(loss='mse', optimizer=Adam(lr=0.001))

# Initialize replay memory
memory = deque(maxlen=2000)
# Hyperparameters
gamma, epsilon, epsilon_min, epsilon_decay = 0.95, 1.0, 0.01, 0.995
batch_size, n_episodes = 32, 10
# Main training loop
for episode in range(n_episodes):
    state, total_reward = env.reset(), 0
    state = np.reshape(state, [1, state_size])

    for time in range(500):
        if np.random.rand() <= epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(model.predict(state)[0])

        next_state, reward, done, _ = env.step(action)
        next_state = np.reshape(next_state, [1, state_size])
        total_reward += reward

        memory.append((state, action, reward, next_state, done))
        state = next_state

        if done:
            print(f"Episode: {episode + 1}, Score: {time + 1}, Epsilon: {epsilon:.2f}")
            break
            
        if len(memory) > batch_size:
            minibatch = random.sample(memory, batch_size)
            for state, action, reward, next_state, done in minibatch:
                target = reward + gamma * np.amax(model.predict(next_state)[0])
                target_f = model.predict(state)
                target_f[0][action] = target
                model.fit(state, target_f, epochs=1, verbose=0)
    epsilon = max(epsilon * epsilon_decay, epsilon_min)

env.close()






AttributeError: module 'keras.src' has no attribute 'utils'